# Generated by Django 4.2.7 on 2023-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.IntegerField(blank=True, db_column='listingId', null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('kilometers', models.CharField(blank=True, max_length=45, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=45, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=45, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=45, null=True)),
                ('seller_type', models.CharField(blank=True, max_length=45, null=True)),
                ('condition', models.CharField(blank=True, max_length=45, null=True)),
                ('suburb', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('transmission', models.CharField(blank=True, max_length=45, null=True)),
                ('body_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drive_type', models.CharField(blank=True, max_length=45, null=True)),
                ('engine', models.CharField(blank=True, max_length=45, null=True)),
                ('fuel_consumption', models.CharField(blank=True, max_length=45, null=True)),
                ('colour_ext', models.CharField(blank=True, max_length=45, null=True)),
                ('colour_int', models.CharField(blank=True, max_length=45, null=True)),
                ('registration', models.CharField(blank=True, max_length=45, null=True)),
                ('vin', models.CharField(blank=True, max_length=45, null=True)),
                ('stock_no', models.CharField(blank=True, max_length=45, null=True)),
                ('dealer', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('make', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('variant', models.CharField(blank=True, max_length=128, null=True)),
                ('series', models.CharField(blank=True, max_length=45, null=True)),
                ('is_sold', models.IntegerField(blank=True, null=True)),
                ('sold_date', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'autotrader',
                'managed': False,
            },
        ),
    ]
